stage={scale:0,focus:{x:0,y:0,scale:0},scene:'level',background:0}
game={level:0,zone:0,edge:{x:0,y:0},tileSize:40}
physics={gravity:0.2,resistance:0.01,friction:0.01}
graphics={main:0,backgrounds:[]}
transition={trigger:false,anim:0,scene:stage.scene}
inputs={mouse:{x:0,y:0},rel:{x:0,y:0},keys:[[false,false,false,false],[false,false,false,false]]}
entities={walls:[],players:[]}
collision={incident:{x:0,y:0},calculate:{x:0,y:0}}
run={fore:[]}
a=0;b=0;c=0;d=0;_=0
la=0;lb=0;lc=0;ld=0